### ISSUE TITLE
Add license to output library

### ISSUE THREAD

**Issue by cwlind** [ashtonfei/gas-libs#1]
Hi Ashton, I suggest adding your copyright/license info as a comment to the top of the [dist/GoogleFormConcatenator.gs] file. Some of us will likely copy the code and insert it into our projects since libraries can be slow at times. I would do that for all your production build scripts. You should get credit for the work you do. :) Thanks for the great work!

**Comment by ashtonfei** [comment]
Thanks for your suggestion, I will update the build script so the license can be added for each build automatically.
